apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana/
- hello/

namespace: fastcampus

commonLabels:
  department: "devops"
  owner: "claud"
commonAnnotations:
  key1: "val1"
  key2: "val2"

replicas:
- name: grafana
  count: 2
- name: hello
  count: 3

images:
- name: grafana/grafana
  newTag: "8.2.2"
- name: nginxdemos/hello
  newName: nginx
  newTag: "latest"
