apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  completions: 4
  parallelism: 1
  activeDeadlineSeconds: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello
        image: ubuntu:focal
        command: ["sh", "-c", "sleep 5; echo Hello World!"]
